model_name: "Qwen/Qwen2.5-Math-1.5B"
output_dir: "0702-1.5B-1to64"
run_name: "0702-1.5B-1to64"
resume_from_checkpoint: False
scale_rewards: True
learning_rate: 1e-6
beta: 0
adam_beta1: 0.9
adam_beta2: 0.99
weight_decay: 0.1
lr_scheduler_type: constant
logging_steps: 1
bf16: True
bf16_full_eval: True
per_device_train_batch_size: 5
per_device_eval_batch_size: 5
gradient_accumulation_steps: 10
gradient_checkpointing: True
num_generations: 25
max_prompt_length: 500
max_completion_length: 4000
save_steps: 25
max_grad_norm: 0.1
report_to: wandb
use_vllm: True
vllm_max_model_len: 4600
max_steps: 400
log_completions: True
evaluation_strategy: steps
eval_steps: 600
eval_on_start: False 
epsilon: 0.2
epsilon_high: 0.4
mask_truncated_completions: True
loss_type: "bnpo"
nsr_enabled: False
num_iterations: 1
all_400: True
# question_index: 2464 (1/256)
# question_index: 2154 (1/256) actually correct
# question_index: 2683 (16/256)
# question_index: 2730 (128/256)
question_index: 2154














# model_name: "Qwen/Qwen2.5-Math-1.5B"
# output_dir: "0625-math-1.5b-all400"
# run_name: "0625-math-1.5b-1q-all400"
# resume_from_checkpoint: False
# scale_rewards: True
# learning_rate: 1e-6
# beta: 0
# adam_beta1: 0.9
# adam_beta2: 0.99
# weight_decay: 0.1
# lr_scheduler_type: constant
# logging_steps: 1
# bf16: True
# bf16_full_eval: True
# per_device_train_batch_size: 5
# per_device_eval_batch_size: 5
# gradient_accumulation_steps: 10
# gradient_checkpointing: True
# num_generations: 30
# max_prompt_length: 500
# max_completion_length: 8000
# save_steps: 25
# max_grad_norm: 0.1
# report_to: wandb
# use_vllm: True
# vllm_max_model_len: 8500
# max_steps: 200
# log_completions: True
# evaluation_strategy: steps
# eval_steps: 600
# eval_on_start: False 
# epsilon: 0.2
# epsilon_high: 0.4
# mask_truncated_completions: True
# loss_type: "bnpo"
# nsr_enabled: False
# num_iterations: 2
# all_400: True
# # question_index: 2464 (1/256)
# # question_index: 2154 (1/256) actually correct
# # question_index: 2683 (16/256)
# # question_index: 2730 (128/256)
# question_index: 2154





